- hosts: routers
  roles:
    - common
    - routers
    - snmp_manager
- hosts: servers
  roles:
    - common
    - servers
    - snmp_agent
    - LDAP_server
- hosts: clients
  roles:
    - common
    - clients