- hosts: routers
  roles:
    - common
    - routers_1setup
    - snmp_manager
- hosts: servers
  roles:
    - common
    - servers
    - snmp_agent
- hosts: clients
  roles:
    - common
    - clients