- name: Restart Slapd
  become: true
  ansible.builtin.service:
    name: slapd
    state: restarted

- name: Reconfigure Slapd
  become: true
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive -p critical --force slapd
