#indirizzo server ldap
address: 10.2.2.21
libnss_ldap:
    - question: "shared/ldapns/base-dn"
      value: dc=labammsis
      vtype: string
    - question: "libnss-ldap/rootbinddn"
      value: cn=admin,dc=labammsis
      vtype: string
    - question: "libnss-ldap/dblogin"
      value: "false"
      vtype: boolean
    - question: "libnss-ldap/confperm" 
      value: false
      vtype: boolean
    - question: "libnss-ldap/dbrootlogin" 
      value: false 
      vtype: boolean
    - question: "shared/ldapns/ldap_version" 
      value: 3 
      vtype: select
    - question: "libnss-ldap/rootbinddn" 
      value: "cn=admin" 
      vtype: string
    - question: "shared/ldapns/ldap-server" 
      value: ldap://{{ address }}
      vtype: string
    - question: "libnss-ldap/override" 
      value: true 
      vtype: boolean
    - question: "libnss-ldap/nsswitch" 
      value: "" 
      vtype: string

libnss_ldap_password:
    - question: "libnss-ldap/rootbindpw"
      value: "gennaio.marzo"

libpam_ldap:
    - question: "shared/ldapns/base-dn"
      value: dc=labammsis 
      vtype: string
    - question: "libpam-ldap/pam_password"
      value: "crypt"
      vtype: string
    - question: "libpam-ldap/dblogin" 
      value: false
      vtype: boolean
    - question: "libpam-ldap/dbrootlogin"
      value: true
      vtype: boolean
    - question: "libpam-ldap/rootbinddn"
      value: "cn=admin,dc=labammsis" 
      vtype: string
    - question: "shared/ldapns/ldap-server"
      value: ldap://{{ address }}
      vtype: string
    - question: "shared/ldapns/ldap_version"
      value: 3
      vtype: select

libpam_ldap_password:
    - question: "libpam-ldap/rootbindpw"
      value: "gennaio.marzo"
      vtype: "password"

files:
    - src: "../files/nsswitch.conf"
      dest: "/etc/nsswitch.conf"
    - src: "../files/ldap.conf"
      dest: "/etc/ldap/ldap.conf"

      