password: gennaio.marzo

users:
 - dn: uid=dave,ou=People,dc=labammsis 
   givenName: Davide
   cn: Davide
   sn: Berardi
   mail: davide.berardi@unibo.it
   uid: dave
   uidNumber: 10000
   gidNumber: 10000
   homeDirectory: /home/dave
   loginShell: /bin/bash
   gecos: Davide "Dave" Berardi
   userPassword: "{crypt}x"
userspassword:
 - uid: dave
   passwd: pippo
usergroups:
 - cn: dave
   gidNumber: 10000