- hosts: routers
  roles:
    - common
    - routers_1_setup
    - snmp_manager
- hosts: servers
  roles:
    - common
    - servers
    - snmp_agent
   # - add_chron_job
- hosts: clients
  roles:
    - common
    - clients