- name: Copy a new network configuration "interfaces" file into place, after passing validation with ifup 
  become: true
  ansible.builtin.copy:
    src: ../files/eth1_cfg_dhcp
    dest: /etc/network/interfaces.d/eth1
    validate: /usr/sbin/ifup --no-act -i %s eth1
  notify: Restart Networking
