
  - name: create user matteo
    become: yes
    ansible.builtin.user:
     name: matteo
     comment: utente_matteo
     password: "{{ 'prova' | password_hash('sha512') }}"
     create_home: yes
     expires: 15552000
  - name: Upload ssh public key in Authorized_key
    become: yes
    ansible.posix.authorized_key:
     user: matteo
     state: present
     key: "{{ lookup('file', '~/.ssh/id_rsa_ansible.pub') }}"
  - name: copy file to remote
    become: yes
    ansible.builtin.copy:
      src: /home/matteo/VMs/vm_virtuale/copy.sh
      dest: /usr/bin/
      owner: root
      mode: 700
  - name: copy file to remote
    become: yes
    ansible.builtin.copy:
      src: /home/matteo/VMs/vm_virtuale/save.list
      dest: /etc
      owner: root
      mode: 700
  - name: Ensure passwd is backed up
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/save.list
      line: /etc/passwd
  - name: Schedule backup
    ansible.builtin.cron:
      name: "backup selected files"
      minute: "*/2"
      weekday: "1-5"
      month: "1-7,9-12"
      job: "/usr/bin/copy.sh 2>/dev/null >/dev/null"
  - name: Guarantee rsyslog is started
    ansible.builtin.systemd:
      name: rsyslog.service
      state: started
  - name: install atd
    become: yes
    ansible.builtin.apt:
      name: at